database:
  protocol: "postgresql"
  host: "127.0.0.1"
  port: "5433"
  name: "leeta"
  user: "postgres"
  password: "postgres"
server:
  httpUrl: "0.0.0.0"
  httpPort: "8080"
  httpAllowedOrigins: "http://127.0.0.1:3000,http://127.0.0.1:8080"
app: 
  name: "leeta"
  env: "development"