services:
  postgres:
    image: postgis/postgis:16-3.5-alpine
    platform: linux/amd64
    container_name: leeta_postgres
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - leeta

  app:
    build: .
    container_name: leeta_app
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - leeta
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  leeta:
    driver: bridge